export default {
  BEGIN_LOADING: 'BEGIN_LOADING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS_ADMIN: 'LOGIN_SUCCESS_ADMIN',
  LOGOUT: 'LOGOUT',
  FETCH_PARTIES_SUCCESS: 'FETCH_PARTIES_SUCCESS',
  FETCH_PARTIES_FAILURE: 'FETCH_PARTIES_FAILURE',
  FETCH_OFFICES_SUCCESS: 'FETCH_OFFICES_SUCCESS',
  FETCH_OFFICES_FAILURE: 'FETCH_OFFICES_FAILURE',
};
